services:
  # ==== БИЗНЕС-СЕРВИСЫ ====
  business-entity-container:
    build:
      context: .
      dockerfile: BusinessEntity/Dockerfile
    container_name: business-entity-container
    ports:
      - "7000:80"
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
      IS_DOCKER: "true"
    depends_on:
      - postgres-production-db
    networks:
      - docker-business-entity-common-bridge
    restart: unless-stopped

  web_logger-container:
    build:
      context: .
      dockerfile: BlazorServerWebLogger/Dockerfile
    container_name: web_logger-container
    ports:
      - "5080:80"
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
      IS_DOCKER: "true"
    depends_on:
      - postgres-production-db
    networks:
      - docker-business-entity-common-bridge
    restart: unless-stopped

  admin-node:
    build:
      context: .
      dockerfile: ControlNode/Dockerfile
    container_name: admin-node
    ports:
      - "5020:80"
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
      IS_DOCKER: "true"
    networks:
      - docker-business-entity-common-bridge
    restart: unless-stopped

  postgres-production-db:
    build:
      context: ./postgres_db
    container_name: postgres-production-db
    ports:
      - "5470:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker-business-entity-common-bridge
    restart: unless-stopped

  # ==== AUTHENTIK (extends, файл в Authentic/ НЕ меняем) ====
  postgresql:
    extends:
      file: ./Authentic/docker-compose.yml
      service: postgresql
    env_file:
      - ./Authentic/.env
    networks:
      - docker-business-entity-common-bridge
    volumes:
      # МОНТИРУЕМ СТАРЫЙ ТОМ С ДАННЫМИ AUTHENTIK:
      - database:/var/lib/postgresql/data

  redis:
    extends:
      file: ./Authentic/docker-compose.yml
      service: redis
    networks:
      - docker-business-entity-common-bridge
    volumes:
      - redis:/data

  server:
    extends:
      file: ./Authentic/docker-compose.yml
      service: server
    env_file:
      - ./Authentic/.env
    networks:
      docker-business-entity-common-bridge:
        aliases:
          - authentic-server-1
    depends_on:
      - postgresql
      - redis

  worker:
    extends:
      file: ./Authentic/docker-compose.yml
      service: worker
    env_file:
      - ./Authentic/.env
    networks:
      - docker-business-entity-common-bridge
    depends_on:
      - postgresql
      - redis

networks:
  docker-business-entity-common-bridge:
    external: true
    name: docker-business-entity-common-bridge

volumes:
  pgdata:
  # Важное изменение: используем внешний том со СТАРЫМИ данными Authentik
  database:
    external: true
    name: authentic_database
  redis:
