<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstract\**" />
    <EmbeddedResource Remove="Abstract\**" />
    <None Remove="Abstract\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleOnlineMall.DataAccess\SampleOnlineMall.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Managers\" />
  </ItemGroup>

</Project>
