<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Classes\Helper\**" />
    <EmbeddedResource Remove="Classes\Helper\**" />
    <None Remove="Classes\Helper\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="20.3.1" />
    <PackageReference Include="ReactiveUI.Blazor" Version="20.3.1" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessEntity.DataAccess\BusinessEntity.DataAccess.csproj" />
    <ProjectReference Include="..\SampleOnlineMall.Service\SampleOnlineMall.Service.csproj" />
  </ItemGroup>

</Project>
