services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: "HNIm7YwTKMK0rFED3cE73A"   # ← ок, как у тебя на скрине
      POSTGRES_USER: "authentik"
      POSTGRES_DB: "authentik"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

  server:
    image: ghcr.io/goauthentik/server:2025.6.0
    command: server
    restart: unless-stopped
    environment:
      AUTHENTIK_SECRET_KEY: "HvitN4vO2BIqovviFmX+1HRPkqGY/1NNJfFbjSLc5nI="  # из твоего .env
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "HNIm7YwTKMK0rFED3cE73A"

      # Bootstrap (одинаково и тут, и в worker!)
      AUTHENTIK_BOOTSTRAP_EMAIL: "be-adm@business-entity.local"
      AUTHENTIK_BOOTSTRAP_PASSWORD: "SuperStrong!123"
      AUTHENTIK_BOOTSTRAP_TOKEN: "5f81e1c4b8c0417c9f7b01a6d83a44dbdf18a27c29b93c4c9b71a9e2e06d1d3c"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    ports:
      - "9000:9000"
      - "9443:9443"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: ghcr.io/goauthentik/server:2025.6.0
    command: worker
    restart: unless-stopped
    environment:
      AUTHENTIK_SECRET_KEY: "HvitN4vO2BIqovviFmX+1HRPkqGY/1NNJfFbjSLc5nI="
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "HNIm7YwTKMK0rFED3cE73A"

      # Тот же bootstrap!
      AUTHENTIK_BOOTSTRAP_EMAIL: "be-adm@business-entity.local"
      AUTHENTIK_BOOTSTRAP_PASSWORD: "SuperStrong!123"
      AUTHENTIK_BOOTSTRAP_TOKEN: "5f81e1c4b8c0417c9f7b01a6d83a44dbdf18a27c29b93c4c9b71a9e2e06d1d3c"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
      - ./blueprints:/blueprints:ro
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
    driver: local
  redis:
    driver: local
